/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ModuloInterfazUsuario;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author nath_
 */
public class Opciones extends javax.swing.JFrame {

    /**
     * Creates new form Opciones
     */
    public Opciones() {
        initComponents();
        opcionesPlan.setVisible(false);
    DesplegablePrecios.addMouseListener(new MouseAdapter() {
    @Override
    public void mouseClicked(MouseEvent e) {
        // Alternar visibilidad
        opcionesPlan.setVisible(!opcionesPlan.isVisible());
    }
});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JPanel();
        Banner = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ContenedorRuta = new javax.swing.JPanel();
        HoraInicio = new javax.swing.JLabel();
        HoraLlegada = new javax.swing.JLabel();
        separador1 = new javax.swing.JLabel();
        trenImagen = new javax.swing.JLabel();
        estacionLlegada = new javax.swing.JLabel();
        EstacionInicio = new javax.swing.JLabel();
        viajeDirecto = new javax.swing.JLabel();
        DuracionTrayecto = new javax.swing.JLabel();
        separador2 = new javax.swing.JLabel();
        DesplegablePrecios = new javax.swing.JPanel();
        precioMinimo = new javax.swing.JLabel();
        Desde = new javax.swing.JLabel();
        moneda = new javax.swing.JLabel();
        iconoParaDesplegar = new javax.swing.JLabel();
        opcionesPlan = new javax.swing.JPanel();
        PlanEjecutivo = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        PlanEstandar = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        PlanPremium = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Contenedor.setBackground(new java.awt.Color(255, 255, 255));
        Contenedor.setPreferredSize(new java.awt.Dimension(1920, 1080));
        Contenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Banner.setBackground(new java.awt.Color(0, 0, 0));
        Banner.setPreferredSize(new java.awt.Dimension(1920, 100));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Roboto ExtraBold", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UrbanLink");

        javax.swing.GroupLayout BannerLayout = new javax.swing.GroupLayout(Banner);
        Banner.setLayout(BannerLayout);
        BannerLayout.setHorizontalGroup(
            BannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BannerLayout.createSequentialGroup()
                .addGap(780, 780, 780)
                .addComponent(jLabel1)
                .addContainerGap(904, Short.MAX_VALUE))
        );
        BannerLayout.setVerticalGroup(
            BannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BannerLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        Contenedor.add(Banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        ContenedorRuta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HoraInicio.setBackground(new java.awt.Color(255, 255, 255));
        HoraInicio.setFont(new java.awt.Font("Roboto ExtraBold", 1, 48)); // NOI18N
        HoraInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HoraInicio.setText("06:00");
        ContenedorRuta.add(HoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        HoraLlegada.setBackground(new java.awt.Color(255, 255, 255));
        HoraLlegada.setFont(new java.awt.Font("Roboto ExtraBold", 1, 48)); // NOI18N
        HoraLlegada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HoraLlegada.setText("07:45");
        ContenedorRuta.add(HoraLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 40, -1, -1));

        separador1.setBackground(new java.awt.Color(255, 255, 255));
        separador1.setFont(new java.awt.Font("Roboto ExtraLight", 1, 48)); // NOI18N
        separador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        separador1.setText("--------------------------");
        ContenedorRuta.add(separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        trenImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mingcute--train-line.png"))); // NOI18N
        ContenedorRuta.add(trenImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, -1, 47));

        estacionLlegada.setFont(new java.awt.Font("Roboto ExtraLight", 0, 12)); // NOI18N
        estacionLlegada.setText("Estación 4");
        ContenedorRuta.add(estacionLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 90, -1, -1));

        EstacionInicio.setFont(new java.awt.Font("Roboto ExtraLight", 0, 12)); // NOI18N
        EstacionInicio.setText("Estación 2");
        ContenedorRuta.add(EstacionInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        viajeDirecto.setFont(new java.awt.Font("Roboto ExtraLight", 0, 12)); // NOI18N
        viajeDirecto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viajeDirecto.setText("Directo");
        ContenedorRuta.add(viajeDirecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, -1));

        DuracionTrayecto.setFont(new java.awt.Font("Roboto ExtraLight", 0, 12)); // NOI18N
        DuracionTrayecto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DuracionTrayecto.setText("1h 45m");
        ContenedorRuta.add(DuracionTrayecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, -1, -1));

        separador2.setBackground(new java.awt.Color(255, 255, 255));
        separador2.setFont(new java.awt.Font("Roboto ExtraLight", 1, 48)); // NOI18N
        separador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        separador2.setText("--------------------------");
        ContenedorRuta.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, -1, -1));

        DesplegablePrecios.setBackground(new java.awt.Color(234, 234, 234));
        DesplegablePrecios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        precioMinimo.setBackground(new java.awt.Color(255, 255, 255));
        precioMinimo.setFont(new java.awt.Font("Roboto ExtraBold", 1, 48)); // NOI18N
        precioMinimo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        precioMinimo.setText("200.000");
        DesplegablePrecios.add(precioMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        Desde.setFont(new java.awt.Font("Roboto ExtraLight", 0, 12)); // NOI18N
        Desde.setText("Desde");
        DesplegablePrecios.add(Desde, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        moneda.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        moneda.setText("COP");
        DesplegablePrecios.add(moneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        iconoParaDesplegar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lucide_chevron-up.png"))); // NOI18N
        iconoParaDesplegar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DesplegablePrecios.add(iconoParaDesplegar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        ContenedorRuta.add(DesplegablePrecios, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 0, 320, 130));

        Contenedor.add(ContenedorRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 1590, 130));

        opcionesPlan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PlanEjecutivo.setBackground(new java.awt.Color(255, 255, 255));
        PlanEjecutivo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PlanEjecutivo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Recomendado");
        jPanel11.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        PlanEjecutivo.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 150, 40));

        jLabel16.setFont(new java.awt.Font("Roboto Condensed SemiBold", 0, 14)); // NOI18N
        jLabel16.setText("COP");
        PlanEjecutivo.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel17.setFont(new java.awt.Font("Roboto ExtraBold", 1, 36)); // NOI18N
        jLabel17.setText("450.000");
        PlanEjecutivo.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel18.setFont(new java.awt.Font("Roboto Condensed SemiBold", 0, 24)); // NOI18N
        jLabel18.setText("Ejecutiva");
        PlanEjecutivo.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel19.setFont(new java.awt.Font("Roboto ExtraLight", 0, 18)); // NOI18N
        jLabel19.setText("Asiento economy");
        PlanEjecutivo.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hugeicons--airplane-seat.png"))); // NOI18N
        PlanEjecutivo.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ph--suitcase-rolling-bold.png"))); // NOI18N
        PlanEjecutivo.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel24.setFont(new java.awt.Font("Roboto ExtraLight", 0, 18)); // NOI18N
        jLabel24.setText("Más completo");
        PlanEjecutivo.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel25.setFont(new java.awt.Font("Roboto ExtraLight", 0, 14)); // NOI18N
        jLabel25.setText("Precio por persona*");
        PlanEjecutivo.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, -1, -1));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Roboto ExtraBold", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Comprar");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        PlanEjecutivo.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 150, 50));

        jLabel26.setFont(new java.awt.Font("Roboto ExtraLight", 0, 18)); // NOI18N
        jLabel26.setText("2 artículos de bodega (80kg)");
        PlanEjecutivo.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        opcionesPlan.add(PlanEjecutivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 420, 530));

        PlanEstandar.setBackground(new java.awt.Color(255, 255, 255));
        PlanEstandar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PlanEstandar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Roboto Condensed SemiBold", 0, 24)); // NOI18N
        jLabel23.setText("Estándar");
        PlanEstandar.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel27.setFont(new java.awt.Font("Roboto ExtraLight", 0, 18)); // NOI18N
        jLabel27.setText("Más ligero");
        PlanEstandar.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel28.setFont(new java.awt.Font("Roboto ExtraBold", 1, 36)); // NOI18N
        jLabel28.setText("200.000");
        PlanEstandar.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel29.setFont(new java.awt.Font("Roboto Condensed SemiBold", 0, 14)); // NOI18N
        jLabel29.setText("COP");
        PlanEstandar.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ph--suitcase-rolling-bold.png"))); // NOI18N
        PlanEstandar.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel31.setFont(new java.awt.Font("Roboto ExtraLight", 0, 18)); // NOI18N
        jLabel31.setText("2 artículos de bodega (80kg)");
        PlanEstandar.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        jLabel32.setFont(new java.awt.Font("Roboto ExtraLight", 0, 18)); // NOI18N
        jLabel32.setText("Asiento estándar");
        PlanEstandar.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hugeicons--airplane-seat.png"))); // NOI18N
        PlanEstandar.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Roboto ExtraBold", 0, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Comprar");
        jPanel8.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        PlanEstandar.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 150, 50));

        jLabel35.setFont(new java.awt.Font("Roboto ExtraLight", 0, 14)); // NOI18N
        jLabel35.setText("Precio por persona*");
        PlanEstandar.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));

        opcionesPlan.add(PlanEstandar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 380, 470));

        PlanPremium.setBackground(new java.awt.Color(255, 255, 255));
        PlanPremium.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel36.setFont(new java.awt.Font("Roboto Condensed SemiBold", 0, 24)); // NOI18N
        jLabel36.setText("Premium");

        jLabel37.setFont(new java.awt.Font("Roboto ExtraLight", 0, 18)); // NOI18N
        jLabel37.setText("Más cómodo");

        jLabel38.setFont(new java.awt.Font("Roboto ExtraBold", 1, 36)); // NOI18N
        jLabel38.setText("500.000");

        jLabel39.setFont(new java.awt.Font("Roboto Condensed SemiBold", 0, 14)); // NOI18N
        jLabel39.setText("COP");

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ph--suitcase-rolling-bold.png"))); // NOI18N

        jLabel41.setFont(new java.awt.Font("Roboto ExtraLight", 0, 18)); // NOI18N
        jLabel41.setText("2 artículos de bodega (80kg)");

        jLabel42.setFont(new java.awt.Font("Roboto ExtraLight", 0, 18)); // NOI18N
        jLabel42.setText("Asiento estándar");

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hugeicons--airplane-seat.png"))); // NOI18N

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));
        jPanel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel12MouseClicked(evt);
            }
        });
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setFont(new java.awt.Font("Roboto ExtraBold", 0, 24)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Comprar");
        jPanel12.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel45.setFont(new java.awt.Font("Roboto ExtraLight", 0, 14)); // NOI18N
        jLabel45.setText("Precio por persona*");

        javax.swing.GroupLayout PlanPremiumLayout = new javax.swing.GroupLayout(PlanPremium);
        PlanPremium.setLayout(PlanPremiumLayout);
        PlanPremiumLayout.setHorizontalGroup(
            PlanPremiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
            .addGroup(PlanPremiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PlanPremiumLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(PlanPremiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel36)
                        .addComponent(jLabel37)
                        .addGroup(PlanPremiumLayout.createSequentialGroup()
                            .addComponent(jLabel39)
                            .addGap(6, 6, 6)
                            .addComponent(jLabel38))
                        .addGroup(PlanPremiumLayout.createSequentialGroup()
                            .addComponent(jLabel40)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel41))
                        .addGroup(PlanPremiumLayout.createSequentialGroup()
                            .addComponent(jLabel43)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel42))
                        .addGroup(PlanPremiumLayout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PlanPremiumLayout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addComponent(jLabel45)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PlanPremiumLayout.setVerticalGroup(
            PlanPremiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
            .addGroup(PlanPremiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PlanPremiumLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel36)
                    .addGap(11, 11, 11)
                    .addComponent(jLabel37)
                    .addGap(48, 48, 48)
                    .addGroup(PlanPremiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PlanPremiumLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel39))
                        .addComponent(jLabel38))
                    .addGap(47, 47, 47)
                    .addGroup(PlanPremiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel40)
                        .addComponent(jLabel41))
                    .addGap(8, 8, 8)
                    .addGroup(PlanPremiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel43)
                        .addComponent(jLabel42))
                    .addGap(28, 28, 28)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(jLabel45)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        opcionesPlan.add(PlanPremium, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 140, -1, -1));

        Contenedor.add(opcionesPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 1590, 680));

        getContentPane().add(Contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        JFrame frame = this;
                Datos inte = new Datos();
                inte.setExtendedState(JFrame.MAXIMIZED_BOTH);
                inte.setVisible(true);
                Timer timer = new Timer(1, new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    frame.setVisible(false);
                    }
                });
                timer.start();
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
         JFrame frame = this;
                Datos inte = new Datos();
                inte.setExtendedState(JFrame.MAXIMIZED_BOTH);
                inte.setVisible(true);
                Timer timer = new Timer(1, new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    frame.setVisible(false);
                    }
                });
                timer.start();
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseClicked
        JFrame frame = this;
                Datos inte = new Datos();
                inte.setExtendedState(JFrame.MAXIMIZED_BOTH);
                inte.setVisible(true);
                Timer timer = new Timer(1, new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    frame.setVisible(false);
                    }
                });
                timer.start();
    }//GEN-LAST:event_jPanel12MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Opciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Banner;
    private javax.swing.JPanel Contenedor;
    private javax.swing.JPanel ContenedorRuta;
    private javax.swing.JLabel Desde;
    private javax.swing.JPanel DesplegablePrecios;
    private javax.swing.JLabel DuracionTrayecto;
    private javax.swing.JLabel EstacionInicio;
    private javax.swing.JLabel HoraInicio;
    private javax.swing.JLabel HoraLlegada;
    private javax.swing.JPanel PlanEjecutivo;
    private javax.swing.JPanel PlanEstandar;
    private javax.swing.JPanel PlanPremium;
    private javax.swing.JLabel estacionLlegada;
    private javax.swing.JLabel iconoParaDesplegar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel moneda;
    private javax.swing.JPanel opcionesPlan;
    private javax.swing.JLabel precioMinimo;
    private javax.swing.JLabel separador1;
    private javax.swing.JLabel separador2;
    private javax.swing.JLabel trenImagen;
    private javax.swing.JLabel viajeDirecto;
    // End of variables declaration//GEN-END:variables
}
